DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;

CREATE TABLE products (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    category VARCHAR(50) NOT NULL
);

CREATE TABLE orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    product_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,

    CONSTRAINT fk_orders_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);

INSERT INTO products (name, price, category)
VALUES
    ('Пицца Маргарита', 550.00, 'Пицца'),
    ('Бургер классический', 390.00, 'Бургеры'),
    ('Картофель фри', 180.00, 'Закуски'),
    ('Кола 0.5', 120.00, 'Напитки');

INSERT INTO orders (customer_name, product_id, quantity)
VALUES
    ('Алексей', 1, 2),
    ('Мария', 2, 1),
    ('Иван', 1, 1),
    ('Ольга', 4, 3),
    ('Дмитрий', 3, 2);